Repository matt035343/devops, pull requests merged in 2020-03, with the labels that each got.

#70 add release workflow
  .github/workflows/githubrelease.yml
Labels: minor

#71 Fixing deploy
  .github/workflows/deploy.yml
Labels: patch

#84 Feature/monitoring
  app/go.mod
  app/go.sum
  app/src/authentication/authentication.go
  app/src/middleware/authentication.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/minitwit.go
  app/src/server/handlers.go
  app/src/server/server.go
  monitoring/docker-compose.yml
  monitoring/prometheus.yml
Labels: enhancement

#86 Fixes #85
  app/src/middleware/monitor.go
Labels: bug

#88 Develop
  .github/workflows/deploy-dev.yml
  README.md
  app/go.mod
  app/go.sum
  app/src/authentication/authentication.go
  app/src/middleware/authentication.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/minitwit.go
  app/src/minitwit_test.go
  app/src/server/handlers.go
  app/src/server/server.go
  app/src/types/ErrorMsgResponse.go
  app/src/types/TweetReponse.go
  app/src/utils/templates.go
  dependency.png
  dependencydiagram.png
  docker-compose.dev.yaml
  docker-compose.prod.yaml
  monitoring/docker-compose.yml
  monitoring/prometheus.yml
  simulator/minitwit_scenario.csv
Labels: minor

#107 Fixes #91
  app/src/authentication/authentication.go
  app/src/database/database.go
  app/src/database/followers.go
  app/src/database/latest.go
  app/src/database/messages.go
  app/src/database/users.go
  app/src/middleware/authentication.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/server/handlers.go
  app/src/server/server.go
  app/src/types/ErrorMsgResponse.go
  app/src/types/FollowRequest.go
  app/src/types/Follower.go
  app/src/types/FollowerResponse.go
  app/src/types/LatestResponse.go
  app/src/types/Message.go
  app/src/types/MessageViewData.go
  app/src/types/RegisterRequest.go
  app/src/types/RequestData.go
  app/src/types/TweetReponse.go
  app/src/types/TweetRequest.go
  app/src/types/User.go
  app/src/utils/errormessages.go
  app/src/utils/templates.go
  app/src/utils/utils.go
Labels: High priority, enhancement

#109 Feature/subsystem division, #95
  app/go.sum
  app/src/client/client.go
  app/src/client/handlers.go
  app/src/database/users.go
  app/src/middleware/authentication.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/minitwit.go
  app/src/minitwit_test.go
  app/src/server/handlers.go
  app/src/server/server.go
  app/src/simulator/handlers.go
  app/src/simulator/simulator.go
Labels: enhancement

#113 Feature/swagger #92
  app/swagger/openapi.json
  docker-compose.yaml
  nginx/nginx.conf
Labels: enhancement

#121 Minor version
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/push.yml
  app/go.sum
  app/src/authentication/authentication.go
  app/src/client/client.go
  app/src/client/handlers.go
  app/src/database/database.go
  app/src/database/followers.go
  app/src/database/latest.go
  app/src/database/messages.go
  app/src/database/users.go
  app/src/middleware/authentication.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/minitwit.go
  app/src/minitwit_test.go
  app/src/server/handlers.go
  app/src/server/server.go
  app/src/simulator/handlers.go
  app/src/simulator/simulator.go
  app/src/static/templates/timeline.html
  app/src/types/ErrorMsgResponse.go
  app/src/types/FollowRequest.go
  app/src/types/Follower.go
  app/src/types/FollowerResponse.go
  app/src/types/LatestResponse.go
  app/src/types/Message.go
  app/src/types/MessageViewData.go
  app/src/types/RegisterRequest.go
  app/src/types/RequestData.go
  app/src/types/TweetReponse.go
  app/src/types/TweetRequest.go
  app/src/types/User.go
  app/src/utils/errormessages.go
  app/src/utils/templates.go
  app/src/utils/utils.go
  app/swagger/openapi.json
  docker-compose.yaml
  nginx/nginx.conf
Labels: minor

#123 patch issue 110
  app/src/simulator/handlers.go
Labels: patch

#126 Change prod to use postgres
  .env.sample
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/push.yml
  app/Dockerfile
  app/go.mod
  app/go.sum
  app/src/database/database.go
  app/src/minitwit.go
  app/src/minitwit_test.go
  app/src/utils/environment.go
  docker-compose.dev.yaml
  docker-compose.prod.yaml
  docker-compose.yaml
  flag-tool/src/flagTool.go
Labels: minor

#122 upload SLA as .docx and .pdf, SLA is 1.0
  SLA 1.0.docx
  SLA 1.0.pdf
Labels: documentation

#136 Develop
  .env.sample
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  app/go.mod
  app/go.sum
  app/src/authentication/authentication.go
  app/src/client/handlers.go
  app/src/database/database.go
  app/src/database/followers.go
  app/src/database/latest.go
  app/src/database/messages.go
  app/src/database/users.go
  app/src/log/log.go
  app/src/middleware/logging.go
  app/src/middleware/middleware.go
  app/src/middleware/monitor.go
  app/src/minitwit.go
  app/src/utils/environment.go
  app/src/utils/templates.go
  app/src/utils/utils.go
  monitoring-logging/docker-compose.yml
  monitoring-logging/logging/elasticsearch/Dockerfile
  monitoring-logging/logging/elasticsearch/config/elasticsearch.yml
  monitoring-logging/logging/kibana/Dockerfile
  monitoring-logging/logging/kibana/config/kibana.yml
  monitoring-logging/logging/logstash/Dockerfile
  monitoring-logging/logging/logstash/config/logstash.yml
  monitoring-logging/logging/logstash/pipeline/logstash.conf
  monitoring-logging/monitoring/prometheus.yml
  monitoring/docker-compose.yml
Labels: minor

#138 Hotfix - changes external monitor frequency from 1 sec to 1 min
  app/src/utils/utils.go
Labels: patch

#139 Hotfix. adds correct url for monitoring
  app/src/utils/utils.go
Labels: patch

#140 Fixes environment variables
  app/src/utils/utils.go
  docker-compose.dev.yaml
  docker-compose.prod.yaml
  docker-compose.yaml
Labels: patch
